server:
  port: 0
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/trainingdb?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
application-description : BookRest API App
application-version : 1.0.0
app.title : Book API For SLK Software
app.license : Open Source- Free me  hai le lo 
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /bookrestapi/swagger-ui.html