spring: 
  application:
    name: basicspringsecuritydemousingdb
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    show-sql: true
